<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dell laptop i3-10 gen newRajshahi, Lapt_527bc8</name>
   <tag></tag>
   <elementGuidId>a52c200c-340b-463d-8b36-069c93882aaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-wrapper']/div/div[3]/div/div[2]/div[4]/div[2]/div/div/div/ul/li[6]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container--2uFyv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dell laptop i3-10 gen newRajshahi, LaptopsTk 37,5007 hours</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-wrapper&quot;)/div[@class=&quot;container--297Nx all&quot;]/div[3]/div[@class=&quot;main-section--3D6zE&quot;]/div[@class=&quot;row--3Vhjr main-container--28aG5 justify-content-flex-start--1Xozy align-items-normal--vaTgD flex-wrap-wrap--2PCx8 flex-direction-row--27fh1 flex--3fKk1&quot;]/div[@class=&quot;sm-col-12--30zDS lg-col-9--20qCf  block--3v-Ow&quot;]/div[@class=&quot;ad-list-container--1UnyA&quot;]/div[1]/div[@class=&quot;ad-list--2Y3ql&quot;]/div[@class=&quot;list-wrapper--t_A02&quot;]/ul[@class=&quot;list--3NxGO&quot;]/li[@class=&quot;normal--2QYVk gtm-normal-ad&quot;]/a[@class=&quot;card-link--3ssYv gtm-ad-item&quot;]/div[@class=&quot;container--2uFyv&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-wrapper']/div/div[3]/div/div[2]/div[4]/div[2]/div/div/div/ul/li[6]/a/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tk 18,500'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dhaka, Laptops'])[2]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/div</value>
   </webElementXpaths>
</WebElementEntity>
